account/urls.py
from django.urls import path
from .views import *

app_name = 'account'
urlpatterns = [
    path('',loginview,name='login'),
]

icioc/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('coding.urls')),
    path('account',include('account.urls')),
]

templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>ICIOC CODING SYSTEM</title>
    <style>
        #customers {
            font-family: Arial, Helvetica, sans-serif;
            border-collapse: collapse;
            width: content-box;
        }

        #customers td, #customers th {
            border: 1px solid #ddd;
            padding: 10px;
            text-align: center;
        }

        #customers tr:nth-child(odd) {
            background-color: #f2f2f2;
        }

        #customers td:hover {
            background-color: #ddd;
        }

        #customers th {
            padding-top: 12px;
            padding-bottom: 12px;
            width: 35%;
            text-align: center;
            background-color: #04AA6D;
            color: white;
        }

        .split {
            z-index: 1;
            top: 0;
            overflow-x: hidden;
            padding-top: 20px;
        }

        .left {
            left: 0;
            background-color: #ffffff;
    </style>

</head>
<body>
<div class="flex-container">

    <h1>ICIOC CODING SYSTEM</h1>

    <table class="flex-container" id="customers">
        <tr>
            <th>Zone</th>
            {% for zone in zones %}
                <td>
                    <a href="{% url 'coding:area' zone.id %}">{{ zone.zone }}</a>
                </td>
            {% endfor %}
        </tr>
        {% if areas %}
            <tr>
                <th>Area</th>
                {% for area in areas %}
                    <td><a href="{% url 'coding:mes' area.id %}">{{ area.area }}</a></td>
                {% endfor %}
            </tr>
        {% endif %}
        {% if mes %}
            </table>
            <table id="customers">
            <tr>
                <th>Main Equipment</th>
                <th>MED</th>
            </tr>
            {% for me in mes %}
                <tr>
                    <td><a href="#">{{ me.area }}{{ me.ME_code }}</a></td>
                </tr>
            {% endfor %}
        {% endif %}
        </table>


</div>


{#	<!--====== Javascripts & Jquery ======-->#}
{#	<script src="{% static 'js/jquery.min.js' %}"></script>#}
{#	<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>#}
{#	<script src="{% static 'js/jquery.hoverIntent.min.js' %}"></script>#}
{#	<script src="{% static 'js/jquery.waypoints.min.js' %}"></script>#}
{#	<script src="{% static 'js/superfish.min.js' %}"></script>#}
{#	<script src="{% static 'js/owl.carousel.min.js' %}"></script>#}
{#	<script src="{% static 'js/bootstrap-input-spinner.js' %}"></script>#}
{#	<script src="{% static 'js/jquery.plugin.min.js' %}"></script>#}
{#	<script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>#}
{#	<script src="{% static 'js/jquery.countdown.min.js' %}"></script>#}
{#	<!-- Main JS File -->#}
{#	<script src="{% static 'js/main.js' %}"></script>#}
{#	<script src="{% static 'js/demos/demo-6.js' %}"></script>#}
{#	<script src="{% static 'js/filter.js' %}"></script>#}
{#	<script src="{% static 'js/ajax.js' %}"></script>#}
{#	<script src="https://unpkg.com/aos@2.3.1/dist/aos.js"></script>#}


<!-- Latest compiled and minified CSS -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">

<!-- Latest compiled JavaScript -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

templates/login.html
<html lang="en">
{% load static %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>I3CH ACS</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.rtl.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/font-awesome/css/font-awesome.min.css' %}">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="stylesheet" href="{% static 'css/index2.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'js/main.js' %}">
    <style>

        .content-account {
            text-align: right;
        }
    </style>
</head>
<body>
<div class="container">
    <div class="row mt-3">
        <div class="col-lg-6 col-md-6 col-xs-12 mx-auto card my-5">
            <div class="card-body">
                <div class="d-flex justify-content-center">
                    <h3>ARCHIVE AND CODING SYSTEM</h3>
                </div><br/>
                <form action="{% url 'account:login' %}" method="post">
                    {% csrf_token %}
                    <div class="content-account">
                        <div class="form-group">
                            <label for="email-phone" class="control-label font-weight-bold">شماره پرسنلی</label>
                            <input type="text" id="email-phone" class="form-control" name="username" placeholder="icioc id code">
                        </div><br/>
                        <div class="form-group">
                            <label for="password" class="control-label font-weight-bold">رمز عبور</label>
                            <input type="password" id="password" class="form-control" name="password" placeholder="password">
                        </div>
                        <div class="d-grid gap-2  mx-auto" style="padding: 20px">
                            <button type="submit" class="btn btn-primary ">ورود به سامانه</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

<script src="{% static 'js/jquery.min.js' %}"></script>


<!-- Boostrap Js  -->
<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/index2.js' %}"></script>


</body>
</html>